// <auto-generated />
//
// HAND-WRITTEN: este Designer.cs fue authored manualmente porque
// `dotnet ef migrations add` no estaba disponible en el entorno del
// apply (la generación del script idempotente se hace vía
// `dotnet ef migrations script --idempotent`).
//
// El snapshot completo del modelo post-D7 vive en
// SgvDbContextModelSnapshot.cs; aquí dejamos un stub mínimo con sólo
// las annotations requeridas. EF Core sólo necesita este método para
// resolver el modelo durante la generación del script.
//
// Si se regenera con `dotnet ef migrations add`, mergeá el archivo
// producido pero verificá que el snapshot coincida con
// SgvDbContextModelSnapshot.cs.
//
// Verificado por `dotnet test --filter
// FullyQualifiedName~DropSoftDeleteMigracion`.
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGV.Infraestructura.Persistencia;

#nullable disable

namespace SGV.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(SgvDbContext))]
    [Migration("20260716120000_DropSoftDeleteFromAspNetUsers")]
    partial class DropSoftDeleteFromAspNetUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            // El snapshot completo del modelo vive en
            // SgvDbContextModelSnapshot.cs. Aquí dejamos sólo las
            // annotations mínimas que EF Core necesita para resolver
            // el modelo durante `dotnet ef migrations script
            // --idempotent`. El contenido real del modelo se valida
            // contra SgvDbContextModelSnapshot al ejecutar los tests
            // de migración.
#pragma warning restore 612, 618
        }
    }
}