// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGV.Infraestructura.Persistencia;

#nullable disable

namespace SGV.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(SgvDbContext))]
    [Migration("20260613022804_InicialSgvo")]
    partial class InicialSgvo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Auditoria.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangedPropertiesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("UserId", "OccurredAt");

                    b.HasIndex("EntityName", "EntityId", "OccurredAt");

                    b.ToTable("Auditorias", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Habilidades.CargoHabilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsObligatoria")
                        .HasColumnType("bit");

                    b.Property<Guid>("HabilidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NivelRequeridoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Ponderacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("HabilidadId");

                    b.HasIndex("NivelRequeridoId");

                    b.HasIndex("CargoId", "HabilidadId")
                        .IsUnique();

                    b.ToTable("CargoHabilidades", null, t =>
                        {
                            t.HasCheckConstraint("CK_CargoHabilidades_Ponderacion", "[Ponderacion] > 0");
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Habilidades.Habilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Habilidades", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Habilidades.NivelHabilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<byte>("ValorNumerico")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ValorNumerico")
                        .IsUnique();

                    b.ToTable("NivelesHabilidad", null, t =>
                        {
                            t.HasCheckConstraint("CK_NivelesHabilidad_ValorNumerico", "[ValorNumerico] BETWEEN 1 AND 4");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Codigo = "Basico",
                            Nombre = "Básico",
                            Orden = 1,
                            ValorNumerico = (byte)1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Codigo = "Intermedio",
                            Nombre = "Intermedio",
                            Orden = 2,
                            ValorNumerico = (byte)2
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Codigo = "Avanzado",
                            Nombre = "Avanzado",
                            Orden = 3,
                            ValorNumerico = (byte)3
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Codigo = "Experto",
                            Nombre = "Experto",
                            Orden = 4,
                            ValorNumerico = (byte)4
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Ocupaciones.Ocupacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PuestoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoAsignacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasFilter("[FechaFin] IS NULL AND [IsDeleted] = 0");

                    b.HasIndex("PuestoId")
                        .IsUnique()
                        .HasFilter("[FechaFin] IS NULL AND [IsDeleted] = 0");

                    b.HasIndex("PersonaId", "FechaInicio", "FechaFin");

                    b.HasIndex("PuestoId", "FechaInicio", "FechaFin");

                    b.ToTable("Ocupaciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ocupaciones_Fechas", "[FechaFin] IS NULL OR [FechaFin] >= [FechaInicio]");
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nivel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Nombre");

                    b.ToTable("Cargos", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.Puesto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("PuestoSuperiorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnidadOrganizativaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PuestoSuperiorId");

                    b.HasIndex("UnidadOrganizativaId");

                    b.ToTable("Puestos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Puestos_PuestoSuperior", "[PuestoSuperiorId] IS NULL OR [PuestoSuperiorId] <> [Id]");
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.UnidadOrganizativa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoUnidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("UnidadPadreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("VigenteDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Nombre");

                    b.HasIndex("UnidadPadreId");

                    b.ToTable("UnidadesOrganizativas", null, t =>
                        {
                            t.HasCheckConstraint("CK_UnidadesOrganizativas_UnidadPadre", "[UnidadPadreId] IS NULL OR [UnidadPadreId] <> [Id]");
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Personas.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Legajo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Legajo")
                        .IsUnique()
                        .HasFilter("[Legajo] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("Apellidos", "Nombres");

                    b.HasIndex("TipoDocumento", "NumeroDocumento")
                        .IsUnique()
                        .HasFilter("[TipoDocumento] IS NOT NULL AND [NumeroDocumento] IS NOT NULL AND [IsDeleted] = 0");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Personas.PersonaHabilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fuente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("HabilidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NivelHabilidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("VerificadoAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HabilidadId");

                    b.HasIndex("NivelHabilidadId");

                    b.HasIndex("PersonaId", "HabilidadId")
                        .IsUnique();

                    b.ToTable("PersonaHabilidades", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.EstadoPostulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EsTerminal")
                        .HasColumnType("bit");

                    b.Property<bool>("EsTerminalPositivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("EstadosPostulacion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Codigo = "Postulado",
                            EsTerminal = false,
                            EsTerminalPositivo = false,
                            Nombre = "Postulado",
                            Orden = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Codigo = "Preseleccionado",
                            EsTerminal = false,
                            EsTerminalPositivo = false,
                            Nombre = "Preseleccionado",
                            Orden = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Codigo = "Entrevistado",
                            EsTerminal = false,
                            EsTerminalPositivo = false,
                            Nombre = "Entrevistado",
                            Orden = 3
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Codigo = "Aprobado",
                            EsTerminal = false,
                            EsTerminalPositivo = false,
                            Nombre = "Aprobado",
                            Orden = 4
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Codigo = "Rechazado",
                            EsTerminal = true,
                            EsTerminalPositivo = false,
                            Nombre = "Rechazado",
                            Orden = 5
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Codigo = "Contratado",
                            EsTerminal = true,
                            EsTerminalPositivo = true,
                            Nombre = "Contratado",
                            Orden = 6
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.EvaluacionPostulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EvaluadoAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvaluadoByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PostulacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PuntajeCompatibilidad")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PuntajeEntrevista")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PuntajeTecnico")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Recomendacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluadoAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PostulacionId");

                    b.ToTable("EvaluacionesPostulacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_EvaluacionesPostulacion_PuntajeCompatibilidad", "[PuntajeCompatibilidad] IS NULL OR ([PuntajeCompatibilidad] >= 0 AND [PuntajeCompatibilidad] <= 100)");

                            t.HasCheckConstraint("CK_EvaluacionesPostulacion_PuntajeEntrevista", "[PuntajeEntrevista] IS NULL OR ([PuntajeEntrevista] >= 0 AND [PuntajeEntrevista] <= 100)");

                            t.HasCheckConstraint("CK_EvaluacionesPostulacion_PuntajeTecnico", "[PuntajeTecnico] IS NULL OR ([PuntajeTecnico] >= 0 AND [PuntajeTecnico] <= 100)");
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.HistorialEstadoPostulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("EstadoAnteriorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstadoNuevoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PostulacionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstadoAnteriorId");

                    b.HasIndex("EstadoNuevoId");

                    b.HasIndex("PostulacionId", "ChangedAt");

                    b.ToTable("HistorialEstadosPostulacion", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.Postulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EstadoPostulacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaPostulacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NivelCompatibilidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PostulanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PuntajeCompatibilidad")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("VacanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstadoPostulacionId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PostulanteId");

                    b.HasIndex("VacanteId", "EstadoPostulacionId");

                    b.HasIndex("VacanteId", "PostulanteId")
                        .IsUnique();

                    b.ToTable("Postulaciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_Postulaciones_PuntajeCompatibilidad", "[PuntajeCompatibilidad] IS NULL OR ([PuntajeCompatibilidad] >= 0 AND [PuntajeCompatibilidad] <= 100)");
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.Postulante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Fuente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombres")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasFilter("[PersonaId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("Apellidos", "Nombres");

                    b.ToTable("Postulantes", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Vacantes.EstadoVacante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EsTerminal")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("EstadosVacante", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Codigo = "Abierta",
                            EsTerminal = false,
                            Nombre = "Abierta",
                            Orden = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Codigo = "EnSeleccion",
                            EsTerminal = false,
                            Nombre = "En Selección",
                            Orden = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Codigo = "Cubierta",
                            EsTerminal = true,
                            Nombre = "Cubierta",
                            Orden = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Codigo = "Cancelada",
                            EsTerminal = true,
                            Nombre = "Cancelada",
                            Orden = 4
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Vacantes.HistorialEstadoVacante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("EstadoAnteriorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstadoNuevoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("VacanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstadoAnteriorId");

                    b.HasIndex("EstadoNuevoId");

                    b.HasIndex("VacanteId", "ChangedAt");

                    b.ToTable("HistorialEstadosVacante", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Vacantes.Vacante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EstadoVacanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PuestoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoVacanteId");

                    b.HasIndex("FechaApertura");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PuestoId");

                    b.HasIndex("EstadoVacanteId", "FechaApertura")
                        .HasFilter("[FechaCierre] IS NULL");

                    b.ToTable("Vacantes", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SGV.Dominio.Habilidades.CargoHabilidad", b =>
                {
                    b.HasOne("SGV.Dominio.Organizacion.Cargo", "Cargo")
                        .WithMany("Habilidades")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Habilidades.Habilidad", "Habilidad")
                        .WithMany()
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Habilidades.NivelHabilidad", "NivelRequerido")
                        .WithMany()
                        .HasForeignKey("NivelRequeridoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Habilidad");

                    b.Navigation("NivelRequerido");
                });

            modelBuilder.Entity("SGV.Dominio.Ocupaciones.Ocupacion", b =>
                {
                    b.HasOne("SGV.Dominio.Personas.Persona", "Persona")
                        .WithMany("Ocupaciones")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Organizacion.Puesto", "Puesto")
                        .WithMany("Ocupaciones")
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.Puesto", b =>
                {
                    b.HasOne("SGV.Dominio.Organizacion.Cargo", "Cargo")
                        .WithMany("Puestos")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Organizacion.Puesto", "PuestoSuperior")
                        .WithMany("PuestosSubordinados")
                        .HasForeignKey("PuestoSuperiorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGV.Dominio.Organizacion.UnidadOrganizativa", "UnidadOrganizativa")
                        .WithMany("Puestos")
                        .HasForeignKey("UnidadOrganizativaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("PuestoSuperior");

                    b.Navigation("UnidadOrganizativa");
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.UnidadOrganizativa", b =>
                {
                    b.HasOne("SGV.Dominio.Organizacion.UnidadOrganizativa", "UnidadPadre")
                        .WithMany("UnidadesHijas")
                        .HasForeignKey("UnidadPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UnidadPadre");
                });

            modelBuilder.Entity("SGV.Dominio.Personas.PersonaHabilidad", b =>
                {
                    b.HasOne("SGV.Dominio.Habilidades.Habilidad", "Habilidad")
                        .WithMany()
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Habilidades.NivelHabilidad", "NivelHabilidad")
                        .WithMany()
                        .HasForeignKey("NivelHabilidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Personas.Persona", "Persona")
                        .WithMany("Habilidades")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("NivelHabilidad");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.EvaluacionPostulacion", b =>
                {
                    b.HasOne("SGV.Dominio.Seleccion.Postulacion", "Postulacion")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("PostulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postulacion");
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.HistorialEstadoPostulacion", b =>
                {
                    b.HasOne("SGV.Dominio.Seleccion.EstadoPostulacion", "EstadoAnterior")
                        .WithMany()
                        .HasForeignKey("EstadoAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGV.Dominio.Seleccion.EstadoPostulacion", "EstadoNuevo")
                        .WithMany()
                        .HasForeignKey("EstadoNuevoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Seleccion.Postulacion", "Postulacion")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("PostulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("Postulacion");
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.Postulacion", b =>
                {
                    b.HasOne("SGV.Dominio.Seleccion.EstadoPostulacion", "EstadoPostulacion")
                        .WithMany()
                        .HasForeignKey("EstadoPostulacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Seleccion.Postulante", "Postulante")
                        .WithMany("Postulaciones")
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Vacantes.Vacante", "Vacante")
                        .WithMany("Postulaciones")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoPostulacion");

                    b.Navigation("Postulante");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.Postulante", b =>
                {
                    b.HasOne("SGV.Dominio.Personas.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SGV.Dominio.Vacantes.HistorialEstadoVacante", b =>
                {
                    b.HasOne("SGV.Dominio.Vacantes.EstadoVacante", "EstadoAnterior")
                        .WithMany()
                        .HasForeignKey("EstadoAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGV.Dominio.Vacantes.EstadoVacante", "EstadoNuevo")
                        .WithMany()
                        .HasForeignKey("EstadoNuevoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Vacantes.Vacante", "Vacante")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SGV.Dominio.Vacantes.Vacante", b =>
                {
                    b.HasOne("SGV.Dominio.Vacantes.EstadoVacante", "EstadoVacante")
                        .WithMany()
                        .HasForeignKey("EstadoVacanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Organizacion.Puesto", "Puesto")
                        .WithMany("Vacantes")
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoVacante");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.Cargo", b =>
                {
                    b.Navigation("Habilidades");

                    b.Navigation("Puestos");
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.Puesto", b =>
                {
                    b.Navigation("Ocupaciones");

                    b.Navigation("PuestosSubordinados");

                    b.Navigation("Vacantes");
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.UnidadOrganizativa", b =>
                {
                    b.Navigation("Puestos");

                    b.Navigation("UnidadesHijas");
                });

            modelBuilder.Entity("SGV.Dominio.Personas.Persona", b =>
                {
                    b.Navigation("Habilidades");

                    b.Navigation("Ocupaciones");
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.Postulacion", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("HistorialEstados");
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.Postulante", b =>
                {
                    b.Navigation("Postulaciones");
                });

            modelBuilder.Entity("SGV.Dominio.Vacantes.Vacante", b =>
                {
                    b.Navigation("HistorialEstados");

                    b.Navigation("Postulaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
