// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGV.Infraestructura.Persistencia;

#nullable disable

namespace SGV.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(SgvDbContext))]
    partial class SgvDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Administrador",
                            ConcurrencyStamp = "rol-Administrador",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "RecursosHumanos",
                            ConcurrencyStamp = "rol-RecursosHumanos",
                            Name = "RecursosHumanos",
                            NormalizedName = "RECURSOSHUMANOS"
                        },
                        new
                        {
                            Id = "GestorOrganizacional",
                            ConcurrencyStamp = "rol-GestorOrganizacional",
                            Name = "GestorOrganizacional",
                            NormalizedName = "GESTORORGANIZACIONAL"
                        },
                        new
                        {
                            Id = "EvaluadorSeleccion",
                            ConcurrencyStamp = "rol-EvaluadorSeleccion",
                            Name = "EvaluadorSeleccion",
                            NormalizedName = "EVALUADORSELECCION"
                        },
                        new
                        {
                            Id = "Lector",
                            ConcurrencyStamp = "rol-Lector",
                            Name = "Lector",
                            NormalizedName = "LECTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Auditoria.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("ChangedPropertiesJson")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("UserId", "OccurredAt");

                    b.HasIndex("EntityName", "EntityId", "OccurredAt");

                    b.ToTable("Auditorias", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Habilidades.CargoHabilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("EsObligatoria")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("HabilidadId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NivelRequeridoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Ponderacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("HabilidadId");

                    b.HasIndex("NivelRequeridoId");

                    b.HasIndex("CargoId", "HabilidadId")
                        .IsUnique();

                    b.ToTable("CargoHabilidades", null, t =>
                        {
                            t.HasCheckConstraint("CK_CargoHabilidades_Ponderacion", "`Ponderacion` > 0");
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Habilidades.Habilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("ActiveCodigoUnique")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(255)")
                        .HasComputedColumnSql("CASE WHEN `IsDeleted` = 0 THEN `Codigo` ELSE NULL END");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCodigoUnique")
                        .IsUnique();

                    b.HasIndex("Categoria");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Habilidades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Categoria = "Conducción",
                            Codigo = "LIDERAZGO",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Liderazgo"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Categoria = "Conducción",
                            Codigo = "GESTION_PERSONAL",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Gestión de Personal"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Categoria = "Técnica",
                            Codigo = "SQL_SERVER",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "SQL Server"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Categoria = "Técnica",
                            Codigo = "EF_CORE",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Entity Framework Core"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            Categoria = "Técnica",
                            Codigo = "DOTNET",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Programación .NET"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000006"),
                            Categoria = "Dominio",
                            Codigo = "ADMINISTRACION_PUBLICA",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Administración Pública"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000007"),
                            Categoria = "Académica",
                            Codigo = "DOCENCIA_UNIVERSITARIA",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Nombre = "Docencia Universitaria"
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Habilidades.NivelHabilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<byte>("ValorNumerico")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ValorNumerico")
                        .IsUnique();

                    b.ToTable("NivelesHabilidad", null, t =>
                        {
                            t.HasCheckConstraint("CK_NivelesHabilidad_ValorNumerico", "`ValorNumerico` BETWEEN 1 AND 4");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Codigo = "Basico",
                            Nombre = "Básico",
                            Orden = 1,
                            ValorNumerico = (byte)1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Codigo = "Intermedio",
                            Nombre = "Intermedio",
                            Orden = 2,
                            ValorNumerico = (byte)2
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Codigo = "Avanzado",
                            Nombre = "Avanzado",
                            Orden = 3,
                            ValorNumerico = (byte)3
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Codigo = "Experto",
                            Nombre = "Experto",
                            Orden = 4,
                            ValorNumerico = (byte)4
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Ocupaciones.Ocupacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ActivePersonaIdUnique")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CASE WHEN `FechaFin` IS NULL AND `IsDeleted` = 0 THEN `PersonaId` ELSE NULL END");

                    b.Property<int?>("ActivePuestoIdUnique")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CASE WHEN `FechaFin` IS NULL AND `IsDeleted` = 0 THEN `PuestoId` ELSE NULL END");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PuestoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TipoAsignacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActivePersonaIdUnique")
                        .IsUnique();

                    b.HasIndex("ActivePuestoIdUnique")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PersonaId", "FechaInicio", "FechaFin");

                    b.HasIndex("PuestoId", "FechaInicio", "FechaFin");

                    b.ToTable("Ocupaciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ocupaciones_Fechas", "`FechaFin` IS NULL OR `FechaFin` >= `FechaInicio`");
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("ActiveCodigoUnique")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(255)")
                        .HasComputedColumnSql("CASE WHEN `IsDeleted` = 0 THEN `Codigo` ELSE NULL END");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nivel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCodigoUnique")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Nombre");

                    b.ToTable("Cargos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Codigo = "DECANO",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Nivel = "Directivo",
                            Nombre = "Decano"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Codigo = "SECRETARIO",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Nivel = "Directivo",
                            Nombre = "Secretario"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Codigo = "DIRECTOR",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Nivel = "Conducción media",
                            Nombre = "Director"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            Codigo = "JEFE_DEPARTAMENTO",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Nivel = "Conducción media",
                            Nombre = "Jefe de Departamento"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            Codigo = "ADMINISTRATIVO",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Nivel = "Operativo",
                            Nombre = "Administrativo"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            Codigo = "PROFESOR",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            Nivel = "Académico",
                            Nombre = "Profesor"
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.Puesto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("ActiveCodigoUnique")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(255)")
                        .HasComputedColumnSql("CASE WHEN `IsDeleted` = 0 THEN `Codigo` ELSE NULL END");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("PuestoSuperiorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UnidadOrganizativaId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCodigoUnique")
                        .IsUnique();

                    b.HasIndex("CargoId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PuestoSuperiorId");

                    b.HasIndex("UnidadOrganizativaId");

                    b.ToTable("Puestos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Puestos_PuestoSuperior", "`PuestoSuperiorId` IS NULL OR `PuestoSuperiorId` <> `Id`");
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.UnidadOrganizativa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("ActiveCodigoUnique")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(255)")
                        .HasComputedColumnSql("CASE WHEN `IsDeleted` = 0 THEN `Codigo` ELSE NULL END");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TipoUnidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("UnidadPadreId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateOnly?>("VigenteDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCodigoUnique")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Nombre");

                    b.HasIndex("UnidadPadreId");

                    b.ToTable("UnidadesOrganizativas", null, t =>
                        {
                            t.HasCheckConstraint("CK_UnidadesOrganizativas_UnidadPadre", "`UnidadPadreId` IS NULL OR `UnidadPadreId` <> `Id`");
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Personas.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("ActiveDocumentoUnique")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(255)")
                        .HasComputedColumnSql("CASE WHEN `TipoDocumento` IS NOT NULL AND `NumeroDocumento` IS NOT NULL AND `IsDeleted` = 0 THEN CONCAT(`TipoDocumento`, ':', `NumeroDocumento`) ELSE NULL END");

                    b.Property<string>("ActiveEmailUnique")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(255)")
                        .HasComputedColumnSql("CASE WHEN `Email` IS NOT NULL AND `IsDeleted` = 0 THEN `Email` ELSE NULL END");

                    b.Property<string>("ActiveLegajoUnique")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(255)")
                        .HasComputedColumnSql("CASE WHEN `Legajo` IS NOT NULL AND `IsDeleted` = 0 THEN `Legajo` ELSE NULL END");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Legajo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDocumentoUnique")
                        .IsUnique();

                    b.HasIndex("ActiveEmailUnique")
                        .IsUnique();

                    b.HasIndex("ActiveLegajoUnique")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Apellidos", "Nombres");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Personas.PersonaHabilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Fuente")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("HabilidadId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NivelHabilidadId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("VerificadoAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("HabilidadId");

                    b.HasIndex("NivelHabilidadId");

                    b.HasIndex("PersonaId", "HabilidadId")
                        .IsUnique();

                    b.ToTable("PersonaHabilidades", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.EstadoPostulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("EsTerminal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsTerminalPositivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("EstadosPostulacion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Codigo = "Postulado",
                            EsTerminal = false,
                            EsTerminalPositivo = false,
                            Nombre = "Postulado",
                            Orden = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Codigo = "Preseleccionado",
                            EsTerminal = false,
                            EsTerminalPositivo = false,
                            Nombre = "Preseleccionado",
                            Orden = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Codigo = "Entrevistado",
                            EsTerminal = false,
                            EsTerminalPositivo = false,
                            Nombre = "Entrevistado",
                            Orden = 3
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Codigo = "Aprobado",
                            EsTerminal = false,
                            EsTerminalPositivo = false,
                            Nombre = "Aprobado",
                            Orden = 4
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Codigo = "Rechazado",
                            EsTerminal = true,
                            EsTerminalPositivo = false,
                            Nombre = "Rechazado",
                            Orden = 5
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Codigo = "Contratado",
                            EsTerminal = true,
                            EsTerminalPositivo = true,
                            Nombre = "Contratado",
                            Orden = 6
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.EvaluacionPostulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("EvaluadoAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EvaluadoByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("PostulacionId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("PuntajeCompatibilidad")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PuntajeEntrevista")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PuntajeTecnico")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Recomendacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluadoAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PostulacionId");

                    b.ToTable("EvaluacionesPostulacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_EvaluacionesPostulacion_PuntajeCompatibilidad", "`PuntajeCompatibilidad` IS NULL OR (`PuntajeCompatibilidad` >= 0 AND `PuntajeCompatibilidad` <= 100)");

                            t.HasCheckConstraint("CK_EvaluacionesPostulacion_PuntajeEntrevista", "`PuntajeEntrevista` IS NULL OR (`PuntajeEntrevista` >= 0 AND `PuntajeEntrevista` <= 100)");

                            t.HasCheckConstraint("CK_EvaluacionesPostulacion_PuntajeTecnico", "`PuntajeTecnico` IS NULL OR (`PuntajeTecnico` >= 0 AND `PuntajeTecnico` <= 100)");
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.HistorialEstadoPostulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChangedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<Guid?>("EstadoAnteriorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EstadoNuevoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("PostulacionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoAnteriorId");

                    b.HasIndex("EstadoNuevoId");

                    b.HasIndex("PostulacionId", "ChangedAt");

                    b.ToTable("HistorialEstadosPostulacion", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.Postulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<Guid>("EstadoPostulacionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaPostulacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NivelCompatibilidad")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("PostulanteId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("PuntajeCompatibilidad")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<Guid>("VacanteId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoPostulacionId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PostulanteId");

                    b.HasIndex("VacanteId", "EstadoPostulacionId");

                    b.HasIndex("VacanteId", "PostulanteId")
                        .IsUnique();

                    b.ToTable("Postulaciones", null, t =>
                        {
                            t.HasCheckConstraint("CK_Postulaciones_PuntajeCompatibilidad", "`PuntajeCompatibilidad` IS NULL OR (`PuntajeCompatibilidad` >= 0 AND `PuntajeCompatibilidad` <= 100)");
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.Postulante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ActivePersonaIdUnique")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("char(36)")
                        .HasComputedColumnSql("CASE WHEN `PersonaId` IS NOT NULL AND `IsDeleted` = 0 THEN `PersonaId` ELSE NULL END");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("Fuente")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombres")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid?>("PersonaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActivePersonaIdUnique")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PersonaId");

                    b.HasIndex("Apellidos", "Nombres");

                    b.ToTable("Postulantes", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Vacantes.EstadoVacante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("EsTerminal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("EstadosVacante", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Codigo = "Abierta",
                            EsTerminal = false,
                            Nombre = "Abierta",
                            Orden = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Codigo = "EnSeleccion",
                            EsTerminal = false,
                            Nombre = "En Selección",
                            Orden = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Codigo = "Cubierta",
                            EsTerminal = true,
                            Nombre = "Cubierta",
                            Orden = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Codigo = "Cancelada",
                            EsTerminal = true,
                            Nombre = "Cancelada",
                            Orden = 4
                        });
                });

            modelBuilder.Entity("SGV.Dominio.Vacantes.HistorialEstadoVacante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChangedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<Guid?>("EstadoAnteriorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EstadoNuevoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("VacanteId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoAnteriorId");

                    b.HasIndex("EstadoNuevoId");

                    b.HasIndex("VacanteId", "ChangedAt");

                    b.ToTable("HistorialEstadosVacante", (string)null);
                });

            modelBuilder.Entity("SGV.Dominio.Vacantes.Vacante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<Guid>("EstadoVacanteId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("PuestoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoVacanteId");

                    b.HasIndex("FechaApertura");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PuestoId");

                    b.HasIndex("EstadoVacanteId", "FechaApertura");

                    b.ToTable("Vacantes", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SGV.Dominio.Habilidades.CargoHabilidad", b =>
                {
                    b.HasOne("SGV.Dominio.Organizacion.Cargo", "Cargo")
                        .WithMany("Habilidades")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Habilidades.Habilidad", "Habilidad")
                        .WithMany()
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Habilidades.NivelHabilidad", "NivelRequerido")
                        .WithMany()
                        .HasForeignKey("NivelRequeridoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Habilidad");

                    b.Navigation("NivelRequerido");
                });

            modelBuilder.Entity("SGV.Dominio.Ocupaciones.Ocupacion", b =>
                {
                    b.HasOne("SGV.Dominio.Personas.Persona", "Persona")
                        .WithMany("Ocupaciones")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Organizacion.Puesto", "Puesto")
                        .WithMany("Ocupaciones")
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.Puesto", b =>
                {
                    b.HasOne("SGV.Dominio.Organizacion.Cargo", "Cargo")
                        .WithMany("Puestos")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Organizacion.Puesto", "PuestoSuperior")
                        .WithMany("PuestosSubordinados")
                        .HasForeignKey("PuestoSuperiorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGV.Dominio.Organizacion.UnidadOrganizativa", "UnidadOrganizativa")
                        .WithMany("Puestos")
                        .HasForeignKey("UnidadOrganizativaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("PuestoSuperior");

                    b.Navigation("UnidadOrganizativa");
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.UnidadOrganizativa", b =>
                {
                    b.HasOne("SGV.Dominio.Organizacion.UnidadOrganizativa", "UnidadPadre")
                        .WithMany("UnidadesHijas")
                        .HasForeignKey("UnidadPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UnidadPadre");
                });

            modelBuilder.Entity("SGV.Dominio.Personas.PersonaHabilidad", b =>
                {
                    b.HasOne("SGV.Dominio.Habilidades.Habilidad", "Habilidad")
                        .WithMany()
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Habilidades.NivelHabilidad", "NivelHabilidad")
                        .WithMany()
                        .HasForeignKey("NivelHabilidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Personas.Persona", "Persona")
                        .WithMany("Habilidades")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");

                    b.Navigation("NivelHabilidad");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.EvaluacionPostulacion", b =>
                {
                    b.HasOne("SGV.Dominio.Seleccion.Postulacion", "Postulacion")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("PostulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postulacion");
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.HistorialEstadoPostulacion", b =>
                {
                    b.HasOne("SGV.Dominio.Seleccion.EstadoPostulacion", "EstadoAnterior")
                        .WithMany()
                        .HasForeignKey("EstadoAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGV.Dominio.Seleccion.EstadoPostulacion", "EstadoNuevo")
                        .WithMany()
                        .HasForeignKey("EstadoNuevoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Seleccion.Postulacion", "Postulacion")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("PostulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("Postulacion");
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.Postulacion", b =>
                {
                    b.HasOne("SGV.Dominio.Seleccion.EstadoPostulacion", "EstadoPostulacion")
                        .WithMany()
                        .HasForeignKey("EstadoPostulacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Seleccion.Postulante", "Postulante")
                        .WithMany("Postulaciones")
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Vacantes.Vacante", "Vacante")
                        .WithMany("Postulaciones")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoPostulacion");

                    b.Navigation("Postulante");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.Postulante", b =>
                {
                    b.HasOne("SGV.Dominio.Personas.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SGV.Dominio.Vacantes.HistorialEstadoVacante", b =>
                {
                    b.HasOne("SGV.Dominio.Vacantes.EstadoVacante", "EstadoAnterior")
                        .WithMany()
                        .HasForeignKey("EstadoAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGV.Dominio.Vacantes.EstadoVacante", "EstadoNuevo")
                        .WithMany()
                        .HasForeignKey("EstadoNuevoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Vacantes.Vacante", "Vacante")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SGV.Dominio.Vacantes.Vacante", b =>
                {
                    b.HasOne("SGV.Dominio.Vacantes.EstadoVacante", "EstadoVacante")
                        .WithMany()
                        .HasForeignKey("EstadoVacanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGV.Dominio.Organizacion.Puesto", "Puesto")
                        .WithMany("Vacantes")
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoVacante");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.Cargo", b =>
                {
                    b.Navigation("Habilidades");

                    b.Navigation("Puestos");
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.Puesto", b =>
                {
                    b.Navigation("Ocupaciones");

                    b.Navigation("PuestosSubordinados");

                    b.Navigation("Vacantes");
                });

            modelBuilder.Entity("SGV.Dominio.Organizacion.UnidadOrganizativa", b =>
                {
                    b.Navigation("Puestos");

                    b.Navigation("UnidadesHijas");
                });

            modelBuilder.Entity("SGV.Dominio.Personas.Persona", b =>
                {
                    b.Navigation("Habilidades");

                    b.Navigation("Ocupaciones");
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.Postulacion", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("HistorialEstados");
                });

            modelBuilder.Entity("SGV.Dominio.Seleccion.Postulante", b =>
                {
                    b.Navigation("Postulaciones");
                });

            modelBuilder.Entity("SGV.Dominio.Vacantes.Vacante", b =>
                {
                    b.Navigation("HistorialEstados");

                    b.Navigation("Postulaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
